export interface CardMeta {
  slug: string;
  name: string;
  pokemon: string;
  set: string;
  setCode: string;
  cardNumber: string;
  artType: string;
  illustrator: string;
  hp: number;
  typing: string;
  stage: string;
  displayOrder: number;
  accentColor: string;
  imageUrl: string;
  imageUrlSmall: string;
}

function buildImageUrls(setCode: string, cardNumber: string) {
  const num = cardNumber.split('/')[0];
  return {
    imageUrl: `https://images.pokemontcg.io/${setCode}/${num}_hires.png`,
    imageUrlSmall: `https://images.pokemontcg.io/${setCode}/${num}.png`,
  };
}

export const CARDS: CardMeta[] = [
  {
    slug: 'umbreon-vmax-215',
    name: 'Umbreon VMAX',
    pokemon: 'Umbreon',
    set: 'Evolving Skies',
    setCode: 'swsh7',
    cardNumber: '215/203',
    artType: 'Alternate Art Secret',
    illustrator: 'Keiichiro Ito',
    hp: 310,
    typing: 'Dark',
    stage: 'VMAX',
    displayOrder: 1,
    accentColor: 'var(--card-umbreon)',
    ...buildImageUrls('swsh7', '215/203'),
  },
  {
    slug: 'rayquaza-vmax-218',
    name: 'Rayquaza VMAX',
    pokemon: 'Rayquaza',
    set: 'Evolving Skies',
    setCode: 'swsh7',
    cardNumber: '218/203',
    artType: 'Alternate Art Secret',
    illustrator: 'Ryuta Fuse',
    hp: 320,
    typing: 'Dragon',
    stage: 'VMAX',
    displayOrder: 2,
    accentColor: 'var(--card-rayquaza)',
    ...buildImageUrls('swsh7', '218/203'),
  },
  {
    slug: 'deoxys-vmax-gg45',
    name: 'Deoxys VMAX',
    pokemon: 'Deoxys',
    set: 'Crown Zenith: Galarian Gallery',
    setCode: 'swsh12pt5gg',
    cardNumber: 'GG45/GG70',
    artType: 'Ultra Rare',
    illustrator: 'Akira Komayama',
    hp: 330,
    typing: 'Psychic',
    stage: 'VMAX',
    displayOrder: 3,
    accentColor: 'var(--card-deoxys)',
    ...buildImageUrls('swsh12pt5gg', 'GG45/GG70'),
  },
  {
    slug: 'gengar-vmax-271',
    name: 'Gengar VMAX',
    pokemon: 'Gengar',
    set: 'Fusion Strike',
    setCode: 'swsh8',
    cardNumber: '271/264',
    artType: 'Alternate Art Secret',
    illustrator: 'Sowsow',
    hp: 320,
    typing: 'Dark',
    stage: 'VMAX',
    displayOrder: 4,
    accentColor: 'var(--card-gengar)',
    ...buildImageUrls('swsh8', '271/264'),
  },
  {
    slug: 'giratina-v-186',
    name: 'Giratina V',
    pokemon: 'Giratina',
    set: 'Lost Origin',
    setCode: 'swsh11',
    cardNumber: '186/196',
    artType: 'Alternate Full Art',
    illustrator: 'Shinji Kanda',
    hp: 220,
    typing: 'Dragon',
    stage: 'V',
    displayOrder: 5,
    accentColor: 'var(--card-giratina)',
    ...buildImageUrls('swsh11', '186/196'),
  },
  {
    slug: 'aerodactyl-v-180',
    name: 'Aerodactyl V',
    pokemon: 'Aerodactyl',
    set: 'Lost Origin',
    setCode: 'swsh11',
    cardNumber: '180/196',
    artType: 'Alternate Full Art',
    illustrator: 'Nurikabe',
    hp: 210,
    typing: 'Fighting',
    stage: 'V',
    displayOrder: 6,
    accentColor: 'var(--card-aerodactyl)',
    ...buildImageUrls('swsh11', '180/196'),
  },
  {
    slug: 'dragonite-v-192',
    name: 'Dragonite V',
    pokemon: 'Dragonite',
    set: 'Evolving Skies',
    setCode: 'swsh7',
    cardNumber: '192/203',
    artType: 'Ultra Rare',
    illustrator: 'Atsushi Furusawa',
    hp: 230,
    typing: 'Dragon',
    stage: 'V',
    displayOrder: 7,
    accentColor: 'var(--card-dragonite)',
    ...buildImageUrls('swsh7', '192/203'),
  },
  {
    slug: 'espeon-v-180',
    name: 'Espeon V',
    pokemon: 'Espeon',
    set: 'Evolving Skies',
    setCode: 'swsh7',
    cardNumber: '180/203',
    artType: 'Ultra Rare',
    illustrator: 'Shibuzoh',
    hp: 200,
    typing: 'Psychic',
    stage: 'V',
    displayOrder: 8,
    accentColor: 'var(--card-espeon)',
    ...buildImageUrls('swsh7', '180/203'),
  },
  {
    slug: 'machamp-v-172',
    name: 'Machamp V',
    pokemon: 'Machamp',
    set: 'Astral Radiance',
    setCode: 'swsh10',
    cardNumber: '172/189',
    artType: 'Ultra Rare',
    illustrator: 'Mitsuhiro Arita',
    hp: 220,
    typing: 'Fighting',
    stage: 'V',
    displayOrder: 9,
    accentColor: 'var(--card-machamp)',
    ...buildImageUrls('swsh10', '172/189'),
  },
  {
    slug: 'tyranitar-v-155',
    name: 'Tyranitar V',
    pokemon: 'Tyranitar',
    set: 'Battle Styles',
    setCode: 'swsh5',
    cardNumber: '155/163',
    artType: 'Ultra Rare',
    illustrator: 'Mitsuhiro Arita',
    hp: 230,
    typing: 'Dark',
    stage: 'V',
    displayOrder: 10,
    accentColor: 'var(--card-tyranitar)',
    ...buildImageUrls('swsh5', '155/163'),
  },
  {
    slug: 'charizard-v-154',
    name: 'Charizard V',
    pokemon: 'Charizard',
    set: 'Brilliant Stars',
    setCode: 'swsh9',
    cardNumber: '154/172',
    artType: 'Alternate Full Art',
    illustrator: 'Ryota Murayama',
    hp: 220,
    typing: 'Fire',
    stage: 'V',
    displayOrder: 11,
    accentColor: 'var(--card-charizard)',
    ...buildImageUrls('swsh9', '154/172'),
  },
  {
    slug: 'starmie-v-tg13',
    name: 'Starmie V',
    pokemon: 'Starmie',
    set: 'Astral Radiance',
    setCode: 'swsh10tg',
    cardNumber: 'TG13/TG30',
    artType: 'Trainer Gallery',
    illustrator: 'Yuu Nishida',
    hp: 190,
    typing: 'Water',
    stage: 'V',
    displayOrder: 12,
    accentColor: 'var(--card-starmie)',
    ...buildImageUrls('swsh10tg', 'TG13/TG30'),
  },
  {
    slug: 'celebi-v-245',
    name: 'Celebi V',
    pokemon: 'Celebi',
    set: 'Fusion Strike',
    setCode: 'swsh8',
    cardNumber: '245/264',
    artType: 'Alternate Full Art',
    illustrator: 'Shibuzoh',
    hp: 190,
    typing: 'Grass',
    stage: 'V',
    displayOrder: 13,
    accentColor: 'var(--card-celebi)',
    ...buildImageUrls('swsh8', '245/264'),
  },
  {
    slug: 'galarian-slowking-v-179',
    name: 'Galarian Slowking V',
    pokemon: 'Galarian Slowking',
    set: 'Chilling Reign',
    setCode: 'swsh6',
    cardNumber: '179/198',
    artType: 'Alternate Full Art',
    illustrator: 'Atsushi Furusawa',
    hp: 220,
    typing: 'Dark',
    stage: 'V',
    displayOrder: 14,
    accentColor: 'var(--card-slowking)',
    ...buildImageUrls('swsh6', '179/198'),
  },
  {
    slug: 'beedrill-v-161',
    name: 'Beedrill V',
    pokemon: 'Beedrill',
    set: 'Astral Radiance',
    setCode: 'swsh10',
    cardNumber: '161/189',
    artType: 'Alternate Full Art',
    illustrator: 'Nurikabe',
    hp: 210,
    typing: 'Grass',
    stage: 'V',
    displayOrder: 15,
    accentColor: 'var(--card-beedrill)',
    ...buildImageUrls('swsh10', '161/189'),
  },
];
